# Generated by Django 4.1 on 2022-09-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meeting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingimages',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='usersinmeeting',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='usersinmeeting',
            name='user',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='MeetingImages',
        ),
        migrations.DeleteModel(
            name='UsersInMeeting',
        ),
    ]
