# Generated by Django 4.1 on 2022-10-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_password_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='url',
        ),
    ]
