# Generated by Django 4.1 on 2022-11-01 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0003_remove_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinmeeting',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to='meeting.meeting'),
        ),
        migrations.AlterField(
            model_name='usersinmeeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', related_query_name='meeting', to=settings.AUTH_USER_MODEL),
        ),
    ]
