# Generated by Django 4.1 on 2022-11-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_usersinmeeting_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingimages',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meeting.meeting', verbose_name='meeting'),
        ),
    ]
