# Generated by Django 4.1 on 2022-11-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0005_alter_meetingimages_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='camera_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='projector_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='meeting end time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_meetings', to=settings.AUTH_USER_MODEL, verbose_name='meeting owner'),
        ),
        migrations.DeleteModel(
            name='UsersInMeeting',
        ),
    ]
